//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagar_bookstore
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail
    {
        public int details_id { get; set; }
        public int o_id { get; set; }
        public int p_id { get; set; }
        public int o_qty { get; set; }
        public decimal o_price { get; set; }
        public decimal o_total { get; set; }
    
        public virtual order order { get; set; }
    }
}
