//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagar_bookstore
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int p_id { get; set; }
        public string p_name { get; set; }
        public decimal p_price { get; set; }
        public int p_qty { get; set; }
        public string p_details { get; set; }
        public int cat_id { get; set; }
        public int o_id { get; set; }
    
        public virtual category category { get; set; }
        public virtual order order { get; set; }
    }
}
